### ISSUE TITLE
MBCord: unhandled promise rejection, error looping after a while

### ISSUE THREAD

**Issue by dragonfire5020** [SandwichFox/MBCord#152]
**Describe the bug**
After a while using MCBord alongside with Discord and Jellyfin it starts entering in an error loop. I *think* the information displaying still works in Discord but you can't click the message away, it will appear continously, you need to exit MBCord to stop that.

**Expected behavior**
No error loop.

**Screenshots**
![Screenshot_10](https://github.com/SandwichFox/MBCord/assets/13822065/17017068-b740-419e-8df4-883872f747f5)

**Error**
`[Sat Nov 11 2023 12:23:13 GMT+0100 (Central European Standard Time)] info: Starting app...
[Sat Nov 11 2023 12:23:13 GMT+0100 (Central European Standard Time)] info: DEBUG INFO:
Development Mode: false
Platform: win32 (Version 10.0.22621)
Architecture: x64
MBCord version: 3.0.7
Node version: 18.12.1
Electron version: 23.1.3
Chrome version: 110.0.5481

[Sat Nov 11 2023 12:23:13 GMT+0100 (Central European Standard Time)] info: Connected to Discord (Server type: jellyfin)
[Sat Nov 11 2023 12:26:36 GMT+0100 (Central European Standard Time)] error: Unhandled Rejection: Error: Unknown Error
    at RPCClient._onRpcMessage (C:\Users\rebor\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\client.js:178:19)
    at IPCTransport.emit (node:events:513:28)
    at C:\Users\rebor\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:138:18
    at decode (C:\Users\rebor\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\rebor\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

[Sat Nov 11 2023 12:26:36 GMT+0100 (Central European Standard Time)] error: Unknown Error
[Sat Nov 11 2023 12:26:40 GMT+0100 (Central European Standard Time)] error: Unhandled Rejection: Error: Unknown Error
    at RPCClient._onRpcMessage (C:\Users\rebor\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\client.js:178:19)
    at IPCTransport.emit (node:events:513:28)
    at C:\Users\rebor\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:138:18
    at decode (C:\Users\rebor\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:92:5)
    at Socket.<anonymous> (C:\Users\rebor\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:120:7)
    at Socket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

[Sat Nov 11 2023 12:26:40 GMT+0100 (Central European Standard Time)] error: Unknown Error`

**Desktop**
 - OS: Windows 11 Enterprise Version Build 22621
 - Server Type: Jellyfin
 - Version 10.8.12

**Additional context**
I'm currently watching with Chrome Canary latest Version because the JMP really sucks currently (no front). But I will check out if the same will happen with using it.

**Comment by dragonfire5020** [comment]
PS: I know this repo is on hold, just want to tell you that nevertheless.
