### ISSUE TITLE
Unclosable error on discord canary update

### ISSUE THREAD

**Issue by bvoo** [SandwichFox/MBCord#23]
```
Error: connection closed
    at C:\Users\bvoo\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\client.js:108:20
    at Map.forEach (<anonymous>)
    at IPCTransport.<anonymous> (C:\Users\bvoo\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\client.js:107:25)
    at Object.onceWrapper (node:events:642:26)
    at IPCTransport.emit (node:events:539:35)
    at IPCTransport.onClose (C:\Users\bvoo\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:151:10)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
```

---

DEBUG INFO:
Development Mode: false
Platform: win32 (Version 10.0.22621)
Architecture: x64
MBCord version: 3.0.5
Node version: 16.16.0
Electron version: 21.2.2
Chrome version: 106.0.5249

**Comment by SandwichFox** [comment]
Could you try to use the normal Discord client, and tell me if its working. Thanks

**Comment by SandwichFox** [comment]
This issue will be marked as stale. If this problem is still happening you can reopen it.
