### ISSUE TITLE
Any way to suppress these?

### ISSUE THREAD

**Issue by KeepBotting** [SandwichFox/MBCord#69]
They pop up over top of all windows <3

```
Error: Unknown Error
    at RPCClient._onRpcMessage (/tmp/.mount_mbcordKreYOr/resources/app.asar/node_modules/discord-rpc/src/client.js:178:19)
    at IPCTransport.emit (node:events:513:28)
    at /tmp/.mount_mbcordKreYOr/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:138:18
    at decode (/tmp/.mount_mbcordKreYOr/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:92:5)
    at Socket.<anonymous> (/tmp/.mount_mbcordKreYOr/resources/app.asar/node_modules/discord-rpc/src/transports/ipc.js:120:7)
    at Socket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

---

DEBUG INFO:
Development Mode: false
Platform: linux (Version 5.15.0-58-generic)
Architecture: x64
MBCord version: 3.0.6
Node version: 16.17.1
Electron version: 22.0.0
Chrome version: 108.0.5359

**Comment by SandwichFox** [comment]
No sadly not, but I will look into whats causing this error

**Comment by SandwichFox** [comment]
I tried to supress these in [v3.0.7](https://github.com/SandwichFox/MBCord/releases/tag/3.0.7). If its still happening just reopen this issue
