### ISSUE TITLE
Closing Discord while MBCord is running

### ISSUE THREAD

**Issue by eelcaz** [SandwichFox/MBCord#72]
I changed the paths in the error message just so it wouldn't show my C drive and such, but the rest of the message is unaltered. To replicate, have MBCord and Discord running, and close discord. You get this error message over and over and the only way to stop it is to end the MBCord task in the Task Manager.
```
Error: connection closed
    at ...\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\client.js:108:20
    at Map.forEach (<anonymous>)
    at IPCTransport.<anonymous> (...\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\client.js:107:25)
    at Object.onceWrapper (node:events:628:26)
    at IPCTransport.emit (node:events:525:35)
    at IPCTransport.onClose (...\AppData\Local\Programs\mbcord\resources\app.asar\node_modules\discord-rpc\src\transports\ipc.js:151:10)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:757:14)
```

---

DEBUG INFO:
Development Mode: false
Platform: win32 (Version 10.0.22621)
Architecture: x64
MBCord version: 3.0.6
Node version: 16.17.1
Electron version: 22.0.0
Chrome version: 108.0.5359

**Comment by SandwichFox** [comment]
Thats normal, MBCord uses your Discord Client to do the Rich Presence, if you want to close Discord close MBCord first. I will write an extension to this in the Wiki
